# Generated by Django 5.2 on 2025-08-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('bronce', 'Liga de Bronce'), ('plata', 'Liga de Plata'), ('oro', 'Liga de Oro'), ('platino', 'Liga de Platino'), ('diamante', 'Liga de Diamante'), ('maestro', 'Liga de Maestros'), ('leyenda', 'Liga de Leyendas')], max_length=50, unique=True)),
                ('puntos_minimos', models.IntegerField(help_text='Puntos mínimos para acceder a esta liga')),
                ('puntos_maximos', models.IntegerField(help_text='Puntos máximos de esta liga')),
                ('icono', models.CharField(default='🏆', max_length=10)),
                ('color_hex', models.CharField(default='#FFD700', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['puntos_minimos'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('especial', 'Evento Especial')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('premio_descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TituloEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='👑', max_length=10)),
                ('color_hex', models.CharField(default='#FFD700', max_length=7)),
                ('condicion_tipo', models.CharField(help_text='Tipo de condición para obtener el título', max_length=50)),
                ('condicion_valor', models.FloatField(help_text='Valor requerido para la condición')),
                ('es_temporal', models.BooleanField(default=False, help_text='Si el título se puede perder')),
                ('puntos_bonus', models.IntegerField(default=0, help_text='Puntos bonus por tener este título')),
            ],
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ranking', models.CharField(choices=[('puntos_totales', 'Puntos Totales'), ('entrenamientos_mes', 'Entrenamientos del Mes'), ('racha_actual', 'Racha Actual'), ('volumen_total', 'Volumen Total Levantado'), ('pruebas_completadas', 'Pruebas Completadas'), ('nivel_arquetipo', 'Nivel de Arquetipo'), ('constancia_semanal', 'Constancia Semanal'), ('records_personales', 'Récords Personales')], max_length=30)),
                ('valor', models.FloatField(help_text='Valor de la métrica para este ranking')),
                ('posicion', models.IntegerField(help_text='Posición en el ranking')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logros.perfilgamificacion')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logros.temporada')),
            ],
            options={
                'ordering': ['posicion'],
                'unique_together': {('perfil', 'temporada', 'tipo_ranking')},
            },
        ),
        migrations.CreateModel(
            name='PerfilTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logros.perfilgamificacion')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logros.tituloespecial')),
            ],
            options={
                'unique_together': {('perfil', 'titulo')},
            },
        ),
    ]
