# Generated by Django 5.2 on 2025-06-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_bitacoradiaria_que_puedo_mejorar_and_more'),
        ('logros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('logro', 'Logro Desbloqueado'), ('mision', 'Misión Completada'), ('nivel', 'Subida de Nivel'), ('racha', 'Racha Conseguida'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('url_accion', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
