# Generated by Django 5.2 on 2025-07-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0002_crear_logros_iniciales'),
        ('rutinas', '0003_ejerciciobase_alter_ejercicioenrutina_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='rutinas.ejerciciobase', verbose_name='Ejercicio relacionado'),
        ),
    ]
