# Generated by Django 5.2 on 2025-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='fecha_fin_evento',
            field=models.DateField(blank=True, help_text='Para misiones especiales con tiempo limitado', null=True, verbose_name='Fecha fin evento'),
        ),
        migrations.AddField(
            model_name='quest',
            name='fecha_inicio_evento',
            field=models.DateField(blank=True, help_text='Para misiones especiales con tiempo limitado', null=True, verbose_name='Fecha inicio evento'),
        ),
        migrations.AddField(
            model_name='quest',
            name='grupo_secuencia',
            field=models.CharField(blank=True, help_text='Identificador del grupo de misiones progresivas', max_length=50, null=True, verbose_name='Grupo de secuencia'),
        ),
        migrations.AddField(
            model_name='quest',
            name='orden_secuencia',
            field=models.IntegerField(blank=True, help_text='Para misiones progresivas, indica el orden en la secuencia', null=True, verbose_name='Orden en secuencia'),
        ),
        migrations.AddField(
            model_name='quest',
            name='requisito_anterior',
            field=models.CharField(blank=True, help_text='Nombre de la misión que debe completarse antes', max_length=100, null=True, verbose_name='Requisito anterior'),
        ),
        migrations.AlterField(
            model_name='tipologro',
            name='categoria',
            field=models.CharField(choices=[('hito', 'Hito'), ('consistencia', 'Consistencia'), ('superacion', 'Superación'), ('especial', 'Especial'), ('exploracion', 'Exploración'), ('equilibrio', 'Equilibrio'), ('social', 'Social'), ('tecnica', 'Técnica'), ('recuperacion', 'Recuperación')], default='hito', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tipoquest',
            name='periodo',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('progresiva', 'Progresiva'), ('permanente', 'Permanente'), ('especial', 'Especial')], default='semanal', max_length=20, verbose_name='Periodo'),
        ),
    ]
