# Generated by Django 5.2 on 2025-07-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_alter_rutina_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ejercicioenrutina',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejerciciobase'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='rutinas.RutinaEjercicio', to='rutinas.ejerciciobase'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejerciciobase'),
        ),
    ]
