# Generated by Django 5.2 on 2025-07-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0007_alter_planpersonalizado_ejercicio_and_more'),
        ('logros', '0003_alter_quest_ejercicio'),
        ('rutinas', '0003_ejerciciobase_alter_ejercicioenrutina_ejercicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ejercicio',
        ),
    ]
