# Generated by Django 5.2 on 2025-07-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0008_ejerciciobase_equipo'),
        ('rutinas', '0004_delete_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='rutinas.RutinaEjercicio', to='entrenos.ejerciciobase'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenos.ejerciciobase'),
        ),
    ]
