# Generated by Django 5.2 on 2025-05-24 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('dietas', '0001_initial'),
        ('rutinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutinas.programa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rutina_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutinas.rutina'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietaasignada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_asignadas_clientes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='dietaasignada',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietas.dieta'),
        ),
        migrations.AddField(
            model_name='objetivocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='revisionprogreso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='objetivocliente',
            unique_together={('cliente', 'medida')},
        ),
    ]
