# Generated by Django 5.2 on 2025-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='entrenos_perfectos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
