# Generated by Django 5.2 on 2025-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_direccion_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='antebrazos',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='biceps',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='caderas',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cintura',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuello',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes_fotos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gemelos',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grasa_corporal',
            field=models.FloatField(blank=True, help_text='%', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hombro',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='muslos',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pecho',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso_corporal',
            field=models.FloatField(blank=True, help_text='kg', null=True),
        ),
    ]
