# Generated by Django 5.2 on 2025-06-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_entrenos_perfectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('horas_sueno', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humor', models.CharField(choices=[('verde', '😊 Bien'), ('amarillo', '😐 Neutro'), ('rojo', '😞 Bajo')], max_length=20)),
                ('rpe', models.PositiveSmallIntegerField(help_text='Esfuerzo percibido (1-10)')),
                ('nota_personal', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
