# Generated by Django 5.2 on 2025-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_antebrazos_cliente_biceps_cliente_caderas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
    ]
