# Generated by Django 5.2 on 2025-06-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_estadosemanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosemanal',
            name='sugerencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
