# Generated by Django 5.2 on 2025-05-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_medida'),
        ('rutinas', '0009_rutinaejercicio_peso_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutinas.programa'),
        ),
    ]
