# Generated by Django 5.2 on 2025-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_bitacoradiaria_peso_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='que_puedo_mejorar',
            field=models.TextField(blank=True, help_text='Reflexiona sobre qué podrías mejorar del día.'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='quien_quiero_ser',
            field=models.TextField(blank=True, help_text='Describe qué tipo de persona quieres ser hoy.'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='reflexion_diaria',
            field=models.TextField(blank=True, help_text='Escribe una reflexión libre sobre tu día.'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='tareas_dia',
            field=models.TextField(blank=True, help_text='Escribe hasta 5 tareas importantes para hoy, separadas por saltos de línea.'),
        ),
    ]
