# Generated by Django 5.2 on 2025-05-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_objetivocliente_unique_together'),
        ('dietas', '0002_remove_dieta_calorias_remove_dieta_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_asignadas_clientes', to='clientes.cliente')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietas.dieta')),
            ],
        ),
    ]
