# Generated by Django 5.2 on 2025-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_bitacoradiaria_dolor_articular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='autoconciencia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Emoción dominante 0–10', null=True),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='descarga_cognitiva',
            field=models.TextField(blank=True, help_text='Preocupaciones actuales', null=True),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='rumiacion_baja',
            field=models.BooleanField(blank=True, help_text='¿La rumiación bajó después de escribir?', null=True),
        ),
    ]
