# Generated by Django 5.2 on 2025-05-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cliente_proximo_registro_peso'),
        ('rutinas', '0013_rutina_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rutina_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutinas.rutina'),
        ),
    ]
