# Generated by Django 5.2 on 2025-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendenciaprogresion',
            name='peso_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tendenciaprogresion',
            name='sesiones_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tendenciaprogresion',
            name='tendencia_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
