# Generated by Django 5.2 on 2025-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_tendenciaprogresion_peso_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendenciaprogresion',
            name='periodo_dias',
            field=models.IntegerField(default=90),
        ),
    ]
