# Generated by Django 5.2 on 2025-06-02 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_entrenos_perfectos'),
        ('entrenos', '0003_entrenorealizado_procesado_gamificacion'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntos_recompensa', models.PositiveIntegerField(default=0, help_text='Puntos que recibe el usuario al desbloquear este logro', verbose_name='Puntos de recompensa')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='logros/', verbose_name='Icono')),
                ('meta_valor', models.PositiveIntegerField(default=1, help_text='Valor numérico que se debe alcanzar para desbloquear el logro', verbose_name='Valor meta')),
                ('es_secreto', models.BooleanField(default=False, help_text='Si es verdadero, el logro no se muestra hasta que se desbloquea', verbose_name='Es secreto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['tipo', 'meta_valor'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Número de nivel')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del nivel')),
                ('puntos_requeridos', models.PositiveIntegerField(help_text='Cantidad de puntos necesarios para alcanzar este nivel', verbose_name='Puntos requeridos')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='niveles/', verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('hito', 'Hito'), ('consistencia', 'Consistencia'), ('superacion', 'Superación'), ('especial', 'Especial')], default='hito', max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Logro',
                'verbose_name_plural': 'Tipos de Logros',
            },
        ),
        migrations.CreateModel(
            name='TipoQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('periodo', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('progresiva', 'Progresiva'), ('permanente', 'Permanente')], default='semanal', max_length=20, verbose_name='Periodo')),
                ('duracion_dias', models.PositiveIntegerField(default=7, help_text='Número de días que dura la misión', verbose_name='Duración en días')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Misión',
                'verbose_name_plural': 'Tipos de Misiones',
            },
        ),
        migrations.CreateModel(
            name='PerfilGamificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.PositiveIntegerField(default=0, verbose_name='Puntos totales')),
                ('fecha_ultimo_entreno', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último entrenamiento')),
                ('racha_actual', models.PositiveIntegerField(default=0, help_text='Días consecutivos de entrenamiento', verbose_name='Racha actual')),
                ('racha_maxima', models.PositiveIntegerField(default=0, help_text='Máximo de días consecutivos de entrenamiento', verbose_name='Racha máxima')),
                ('entrenos_totales', models.PositiveIntegerField(default=0, verbose_name='Entrenamientos totales')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificacion', to='clientes.cliente', verbose_name='Cliente')),
                ('nivel_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='logros.nivel', verbose_name='Nivel actual')),
            ],
            options={
                'verbose_name': 'Perfil de Gamificación',
                'verbose_name_plural': 'Perfiles de Gamificación',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntos_recompensa', models.PositiveIntegerField(default=100, help_text='Puntos que recibe el usuario al completar esta misión', verbose_name='Puntos de recompensa')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='quests/', verbose_name='Icono')),
                ('meta_valor', models.PositiveIntegerField(default=1, help_text='Valor numérico que se debe alcanzar para completar la misión', verbose_name='Valor meta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='rutinas.ejercicio', verbose_name='Ejercicio relacionado')),
                ('quest_padre', models.ForeignKey(blank=True, help_text='Para misiones progresivas que forman parte de una serie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_hijos', to='logros.quest', verbose_name='Misión padre')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='logros.tipoquest', verbose_name='Tipo de misión')),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(verbose_name='Puntos')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('entreno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos', to='entrenos.entrenorealizado', verbose_name='Entrenamiento')),
                ('logro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_otorgados', to='logros.logro', verbose_name='Logro')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='logros.perfilgamificacion', verbose_name='Perfil')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_otorgados', to='logros.quest', verbose_name='Misión')),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historial de Puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='logro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='logros.tipologro', verbose_name='Tipo de logro'),
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de desbloqueo')),
                ('progreso_actual', models.PositiveIntegerField(default=0, verbose_name='Progreso actual')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logros.logro', verbose_name='Logro')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='logros.perfilgamificacion', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'ordering': ['-fecha_desbloqueo'],
                'unique_together': {('perfil', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='QuestUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('progreso_actual', models.PositiveIntegerField(default=0, verbose_name='Progreso actual')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='logros.perfilgamificacion', verbose_name='Perfil')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logros.quest', verbose_name='Misión')),
            ],
            options={
                'verbose_name': 'Misión de Usuario',
                'verbose_name_plural': 'Misiones de Usuarios',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('perfil', 'quest')},
            },
        ),
    ]
