# Generated by Django 5.2 on 2025-06-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0014_bitacoradiaria_circunferencia_biceps_and_more'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado Emocional',
                'verbose_name_plural': 'Estados Emocionales',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntrenoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('procesado_gamificacion', models.BooleanField(default=False)),
                ('fuente_datos', models.CharField(choices=[('manual', 'Manual'), ('liftin', 'Liftin')], default='manual', help_text='Origen de los datos del entrenamiento', max_length=20)),
                ('liftin_workout_id', models.CharField(blank=True, help_text='ID único del entrenamiento en Liftin', max_length=100, null=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio del entrenamiento (ej: 09:43)', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de finalización del entrenamiento (ej: 10:46)', null=True)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, help_text='Duración total del entrenamiento en minutos', null=True)),
                ('tiempo_total_formateado', models.CharField(blank=True, help_text='Tiempo total como aparece en Liftin (ej: 1:02:23)', max_length=20, null=True)),
                ('numero_ejercicios', models.PositiveIntegerField(blank=True, help_text='Número total de ejercicios realizados', null=True)),
                ('volumen_total_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Volumen total levantado en kg (ej: 19000.00 para 19K KG)', max_digits=10, null=True)),
                ('volumen_total_formateado', models.CharField(blank=True, help_text='Volumen como aparece en Liftin (ej: 19K KG)', max_length=20, null=True)),
                ('calorias_quemadas', models.PositiveIntegerField(blank=True, help_text='Calorías quemadas durante el entrenamiento', null=True)),
                ('frecuencia_cardiaca_promedio', models.PositiveIntegerField(blank=True, help_text='Frecuencia cardíaca promedio en BPM', null=True)),
                ('frecuencia_cardiaca_maxima', models.PositiveIntegerField(blank=True, help_text='Frecuencia cardíaca máxima en BPM', null=True)),
                ('nombre_rutina_liftin', models.CharField(blank=True, help_text='Nombre de la rutina como aparece en Liftin (ej: Día 6 - Full Body)', max_length=200, null=True)),
                ('notas_liftin', models.TextField(blank=True, help_text='Notas adicionales importadas de Liftin', null=True)),
                ('fecha_importacion', models.DateTimeField(blank=True, help_text='Fecha y hora de importación desde Liftin', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
            options={
                'verbose_name': 'Entrenamiento Realizado',
                'verbose_name_plural': 'Entrenamientos Realizados',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioLiftinDetallado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(help_text='Nombre del ejercicio como aparece en Liftin', max_length=200)),
                ('orden_ejercicio', models.PositiveIntegerField(default=1, help_text='Orden del ejercicio en la rutina')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso utilizado en kg', max_digits=8, null=True)),
                ('peso_formateado', models.CharField(blank=True, help_text='Peso como aparece en Liftin (ej: 268.5 kg, PC, 90-100 kg)', max_length=50, null=True)),
                ('series_realizadas', models.PositiveIntegerField(default=1, help_text='Número de series realizadas')),
                ('repeticiones_formateado', models.CharField(blank=True, help_text='Repeticiones como aparecen en Liftin (ej: 3x5-10, 3x10-12)', max_length=50, null=True)),
                ('repeticiones_min', models.PositiveIntegerField(blank=True, help_text='Repeticiones mínimas por serie', null=True)),
                ('repeticiones_max', models.PositiveIntegerField(blank=True, help_text='Repeticiones máximas por serie', null=True)),
                ('completado', models.BooleanField(default=True, help_text='Si el ejercicio fue completado exitosamente')),
                ('estado_liftin', models.CharField(choices=[('completado', '✓ Completado'), ('fallado', '✗ Fallado'), ('nuevo', 'N Nuevo'), ('parcial', '~ Parcial')], default='completado', help_text='Estado del ejercicio según Liftin', max_length=20)),
                ('notas_ejercicio', models.TextField(blank=True, help_text='Notas específicas de este ejercicio', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_liftin_detallados', to='entrenos.entrenorealizado')),
            ],
            options={
                'verbose_name': 'Ejercicio Detallado de Liftin',
                'verbose_name_plural': 'Ejercicios Detallados de Liftin',
                'ordering': ['entreno', 'orden_ejercicio'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioLiftin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del ejercicio (ej: Prensa, Curl Femoral Tumbado)', max_length=200)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden del ejercicio en la rutina')),
                ('peso_texto', models.CharField(blank=True, help_text='Peso como aparece en Liftin (ej: 268.5 kg, PC, 90-100 kg)', max_length=50, null=True)),
                ('repeticiones_texto', models.CharField(blank=True, help_text='Repeticiones como aparecen en Liftin (ej: 3x5-10, 3x10-12)', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('completado', '✓ Completado'), ('fallado', '✗ Fallado'), ('nuevo', 'N Nuevo'), ('parcial', '~ Parcial')], default='completado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_liftin', to='entrenos.entrenorealizado')),
            ],
            options={
                'verbose_name': 'Ejercicio de Liftin',
                'verbose_name_plural': 'Ejercicios de Liftin',
                'ordering': ['entreno', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEjercicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completado', models.BooleanField(default=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entrenos.entrenorealizado')),
            ],
        ),
        migrations.CreateModel(
            name='DatosLiftinDetallados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_frecuencia_cardiaca', models.JSONField(blank=True, help_text='Array de datos de frecuencia cardíaca con timestamps', null=True)),
                ('version_liftin', models.CharField(blank=True, max_length=20, null=True)),
                ('dispositivo_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('sincronizado_health', models.BooleanField(default=False)),
                ('health_workout_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('metadatos_adicionales', models.JSONField(blank=True, help_text='Otros datos específicos de Liftin en formato JSON', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entreno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_liftin', to='entrenos.entrenorealizado')),
            ],
            options={
                'verbose_name': 'Datos Detallados de Liftin',
                'verbose_name_plural': 'Datos Detallados de Liftin',
            },
        ),
        migrations.CreateModel(
            name='LogroDesbloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenos.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='SerieRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_numero', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='entrenos.entrenorealizado')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones_objetivo', models.PositiveIntegerField(default=10)),
                ('peso_objetivo', models.FloatField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
            options={
                'unique_together': {('cliente', 'ejercicio', 'rutina')},
            },
        ),
    ]
