# Generated by Django 5.2 on 2025-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0003_registrowhoop_hrv_registrowhoop_rhr'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrowhoop',
            name='eficiencia_sueno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrowhoop',
            name='estres_sueno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrowhoop',
            name='horas_vs_necesidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrowhoop',
            name='regularidad_sueno',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
