# Generated by Django 5.2 on 2025-05-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cliente_proximo_registro_peso'),
        ('entrenos', '0001_initial'),
        ('rutinas', '0012_remove_programa_descripcion_programa_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEjercicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entrenos.entrenorealizado')),
            ],
        ),
    ]
