# Generated by Django 5.2 on 2025-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0002_entrenorealizado_detalleejerciciorealizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleejerciciorealizado',
            name='series',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
