# Generated by Django 5.2 on 2025-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0002_estadoemocional_logrodesbloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='procesado_gamificacion',
            field=models.BooleanField(default=False),
        ),
    ]
