# Generated by Django 5.2 on 2025-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0003_detalleejerciciorealizado_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleejerciciorealizado',
            name='completado',
            field=models.BooleanField(default=True),
        ),
    ]
