# Generated by Django 5.2 on 2025-05-16 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0004_detalleejerciciorealizado_completado'),
        ('rutinas', '0014_ejercicioenrutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_numero', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='entrenos.entrenorealizado')),
            ],
        ),
    ]
