# Generated by Django 5.2 on 2025-05-18 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0005_serierealizada'),
        ('rutinas', '0014_ejercicioenrutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlanPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones_objetivo', models.PositiveIntegerField(default=10)),
                ('peso_objetivo', models.FloatField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenos.cliente')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenos.rutina')),
            ],
            options={
                'unique_together': {('cliente', 'ejercicio', 'rutina')},
            },
        ),
    ]
