# Generated by Django 5.2 on 2025-05-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_rutina_actual'),
        ('entrenos', '0006_serierealizada_completado_planpersonalizado'),
        ('rutinas', '0014_ejercicioenrutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpersonalizado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='planpersonalizado',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
