# Generated by Django 5.2 on 2025-08-13 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(help_text='Día del año (1-366)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)])),
                ('mes', models.CharField(max_length=20)),
                ('tema', models.CharField(max_length=100)),
                ('cita', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('reflexion', models.TextField()),
                ('pregunta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido Diario',
                'verbose_name_plural': 'Contenidos Diarios',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='LogroEstoico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('dias_consecutivos', 'Días Consecutivos'), ('total_reflexiones', 'Total de Reflexiones'), ('tema_completado', 'Tema Completado'), ('filosofo_explorado', 'Filósofo Explorado'), ('calidad_reflexion', 'Calidad de Reflexión')], max_length=20)),
                ('criterio_valor', models.PositiveIntegerField(help_text='Valor necesario para desbloquear el logro')),
                ('icono', models.CharField(default='🏆', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logro Estoico',
                'verbose_name_plural': 'Logros Estoicos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion_matutina', models.BooleanField(default=True)),
                ('hora_matutina', models.TimeField(default='08:00')),
                ('notificacion_vespertina', models.BooleanField(default=True)),
                ('hora_vespertina', models.TimeField(default='20:00')),
                ('recordatorio_reflexion', models.BooleanField(default=True)),
                ('frecuencia_recordatorio', models.PositiveSmallIntegerField(default=2, help_text='Horas entre recordatorios')),
                ('dias_semana', models.JSONField(default=list, help_text='Días de la semana activos (0=Lunes, 6=Domingo)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones_estoicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_activos', models.PositiveIntegerField(default=0)),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('racha_maxima', models.PositiveIntegerField(default=0)),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tiempo_total_reflexion', models.PositiveIntegerField(default=0)),
                ('temas_completados', models.JSONField(default=list)),
                ('filosofos_explorados', models.JSONField(default=list)),
                ('fecha_ultima_actividad', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_estoicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Usuario',
                'verbose_name_plural': 'Estadísticas de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilEstoico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('dias_consecutivos', models.PositiveIntegerField(default=0)),
                ('total_reflexiones', models.PositiveIntegerField(default=0)),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('hora_notificacion', models.TimeField(default='08:00')),
                ('filosofo_favorito', models.CharField(choices=[('marco_aurelio', 'Marco Aurelio'), ('seneca', 'Séneca'), ('epicteto', 'Epicteto'), ('musonio_rufo', 'Musonio Rufo'), ('zenon', 'Zenón de Citio')], default='marco_aurelio', max_length=50)),
                ('tema_favorito', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estoico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Estoico',
                'verbose_name_plural': 'Perfiles Estoicos',
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoico.logroestoico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_estoicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'unique_together': {('usuario', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='ReflexionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('reflexion_personal', models.TextField(help_text='Respuesta del usuario a la pregunta del día')),
                ('calificacion_dia', models.PositiveSmallIntegerField(blank=True, help_text='Calificación del día (1-5 estrellas)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tiempo_reflexion', models.PositiveIntegerField(default=0, help_text='Tiempo en segundos dedicado a la reflexión')),
                ('marcado_favorito', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('contenido_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoico.contenidodiario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflexiones_estoicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflexión Diaria',
                'verbose_name_plural': 'Reflexiones Diarias',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
