# Generated by Django 5.2 on 2025-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='dia',
        ),
        migrations.AddField(
            model_name='rutina',
            name='duracion_minutos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
