# Generated by Django 5.2 on 2025-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_remove_rutina_cliente_remove_rutina_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
            ],
        ),
    ]
