# Generated by Django 5.2 on 2025-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_rutina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(blank=True, related_name='rutinas', to='rutinas.ejercicio'),
        ),
    ]
