# Generated by Django 5.2 on 2025-05-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_remove_rutina_descripcion_rutina_ejercicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicios',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.programa'),
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField(default=10)),
                ('series', models.IntegerField(default=3)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='rutinas.rutina')),
            ],
        ),
    ]
