# Generated by Django 5.2 on 2025-05-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_remove_rutina_ejercicios_alter_rutina_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='rutinas.RutinaEjercicio', to='rutinas.ejercicio'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='rutinas.programa'),
        ),
    ]
