# Generated by Django 5.2 on 2025-05-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0008_rutina_ejercicios_alter_rutina_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='repeticiones',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='series',
            field=models.PositiveIntegerField(),
        ),
    ]
