# Generated by Django 5.2 on 2025-05-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_programa'),
        ('rutinas', '0009_rutinaejercicio_peso_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.programa')),
            ],
        ),
    ]
