# Generated by Django 5.2 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0010_alter_programa_descripcion_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='icono',
            field=models.CharField(choices=[('arco.png', 'Arco'), ('rutinas_ad_hoc.png', 'Rutinas Ad Hoc'), ('cero_hipertrofia.png', 'Cero Hipertrofia'), ('entreno_hipertrofia.png', 'Entreno Hipertrofia'), ('fit.png', 'Fit'), ('hipertrofia_avanzado.png', 'Hipertrofia Avanzado')], default='arco.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
