# Generated by Django 5.2 on 2025-05-15 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0011_programa_icono_alter_programa_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
