# Generated by Django 5.2 on 2025-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0012_remove_programa_descripcion_programa_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
