# Generated by Django 5.2 on 2025-05-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0013_rutina_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioEnRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('series_default', models.PositiveIntegerField(default=3)),
                ('repeticiones_default', models.PositiveIntegerField(default=10)),
                ('peso_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_asignados', to='rutinas.rutina')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('rutina', 'ejercicio')},
            },
        ),
    ]
