"""
Django settings for gymproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m^_f1+)gb!61wnzpvso)w7jhv1keu_o6@zs7yna@$$i1*2(&_z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []

# El nombre del host de Render se añade automáticamente si está disponible
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'clientes.apps.ClientesConfig',
    'rutinas',
    'dietas',
    'entrenos',
    'widget_tweaks',
    'joi',
    'logros',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
USE_I18N = True
ROOT_URLCONF = 'gymproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'joi.context_processors.joi_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'gymproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Reemplaza este valor por defecto con tu URL de SQLite local
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'joi', 'static'),  # Añade esta línea
]

# Asegúrate de que STATICFILES_DIRS también esté configurado
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/redirigir/'  # Ruta intermedia para decidir a dónde ir

LOGIN_URL = '/login/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ANALYTICS_CONFIG = {
    'CACHE_TIMEOUT': 3600,  # 1 hora
    'PREDICCION_DIAS_FUTURO': 30,
    'MIN_DATOS_PREDICCION': 10,
    'ALGORITMOS_HABILITADOS': [
        'regresion_lineal',
        'media_movil',
        'tendencia_exponencial'
    ]
}
# Configuración de cache para IA (opcional pero recomendado)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
# En settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file_ia': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/ia.log',
        },
    },
    'loggers': {
        'analytics.ia': {
            'handlers': ['file_ia'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'gamificacion': {
            'format': '🎮 {asctime} - {levelname} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'gamificacion_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'gamificacion.log'),
            'formatter': 'gamificacion',
            'encoding': 'utf-8',
        },
        'gamificacion_console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'gamificacion',
        },
        'gamificacion_debug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'gamificacion_debug.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'gamificacion': {
            'handlers': ['gamificacion_file', 'gamificacion_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gamificacion.debug': {
            'handlers': ['gamificacion_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Mensaje de confirmación
print("✅ Configuración de logging para gamificación cargada")
print(f"📁 Logs se guardarán en: {LOGS_DIR}")

# ============================================================================
# CONFIGURACIÓN ADICIONAL PARA GAMIFICACIÓN
# ============================================================================

# Configuraciones específicas para el sistema de gamificación
GAMIFICACION_CONFIG = {
    'AUTO_PROCESS': True,  # Procesamiento automático activado
    'LOG_LEVEL': 'INFO',  # Nivel de logging
    'VALIDATE_INTEGRITY': True,  # Validación de integridad activada
    'NOTIFICATION_ENABLED': True,  # Notificaciones activadas
}
