# Generated by Django 5.2 on 2025-08-13 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('peso', models.FloatField()),
                ('altura', models.IntegerField()),
                ('nivel_actividad', models.CharField(choices=[('Sedentario', 'Sedentario'), ('Ligeramente activo', 'Ligeramente activo'), ('Activo', 'Activo'), ('Muy activo', 'Muy activo')], max_length=50)),
                ('objetivo', models.CharField(choices=[('Pérdida de grasa', 'Pérdida de grasa'), ('Mantenimiento', 'Mantenimiento'), ('Ganancia muscular', 'Ganancia muscular')], max_length=50)),
                ('experiencia', models.CharField(choices=[('Novato', 'Novato'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Intermedio', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionNivel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatina', models.BooleanField(default=False)),
                ('proteina_polvo', models.BooleanField(default=False)),
                ('multivitaminico', models.BooleanField(default=False)),
                ('omega3', models.BooleanField(default=False)),
                ('vitamina_d', models.BooleanField(default=False)),
                ('otros_suplementos', models.TextField(blank=True, null=True)),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionNivel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comidas_por_dia', models.IntegerField(blank=True, null=True)),
                ('timing_pre_entreno', models.TextField(blank=True, null=True)),
                ('timing_post_entreno', models.TextField(blank=True, null=True)),
                ('distribucion_macros', models.TextField(blank=True, null=True)),
                ('refeeds_configurados', models.BooleanField(default=False)),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionNivel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua_litros', models.FloatField(blank=True, null=True)),
                ('frutas_porciones', models.IntegerField(blank=True, null=True)),
                ('verduras_porciones', models.IntegerField(blank=True, null=True)),
                ('suplementos_recomendados', models.TextField(blank=True, null=True)),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteina_gramos', models.FloatField()),
                ('grasa_gramos', models.FloatField()),
                ('carbohidratos_gramos', models.FloatField()),
                ('proteina_calorias', models.FloatField()),
                ('grasa_calorias', models.FloatField()),
                ('carbohidratos_calorias', models.FloatField()),
                ('proteina_porcentaje', models.FloatField()),
                ('grasa_porcentaje', models.FloatField()),
                ('carbohidratos_porcentaje', models.FloatField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_mantenimiento', models.FloatField()),
                ('calorias_objetivo', models.FloatField()),
                ('factor_actividad', models.FloatField()),
                ('deficit_superavit_porcentaje', models.FloatField()),
                ('metodo_calculo', models.CharField(max_length=50)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion_app_django.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'nivel')},
            },
        ),
    ]
