# Generated by Django 5.2 on 2025-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('horas_sueno', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humor', models.CharField(choices=[('verde', '😊 Bien'), ('amarillo', '😐 Neutro'), ('rojo', '😞 Bajo')], max_length=20)),
                ('rpe', models.PositiveSmallIntegerField(help_text='Esfuerzo percibido (1-10)')),
                ('nota_personal', models.TextField(blank=True)),
                ('mindfulness_am', models.BooleanField(default=False)),
                ('mindfulness_pm', models.BooleanField(default=False)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('energia_subjetiva', models.PositiveSmallIntegerField(blank=True, help_text='Energía subjetiva de 0 a 10', null=True)),
                ('dolor_articular', models.PositiveSmallIntegerField(blank=True, help_text='Dolor articular de 0 a 10', null=True)),
                ('autoconciencia', models.TextField(blank=True, help_text='¿Qué emoción domina (0-10)?', null=True)),
                ('descarga_cognitiva', models.TextField(blank=True, help_text='Escribe 5’ “lo que me preocupa AHORA”', null=True)),
                ('rumiacion_baja', models.BooleanField(blank=True, help_text='¿La rumiación bajó después de escribir?', null=True)),
                ('circunferencia_biceps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emocion_dia', models.CharField(blank=True, max_length=100)),
                ('cosas_positivas', models.TextField(blank=True, help_text='Escribe 3 cosas que funcionaron hoy.')),
                ('aprendizaje', models.TextField(blank=True)),
                ('quien_quiero_ser', models.TextField(blank=True, help_text='Describe qué tipo de persona quieres ser hoy.')),
                ('tareas_dia', models.TextField(blank=True, help_text='Escribe hasta 5 tareas importantes para hoy, separadas por saltos de línea.')),
                ('que_puedo_mejorar', models.TextField(blank=True, help_text='Reflexiona sobre qué podrías mejorar del día.')),
                ('reflexion_diaria', models.TextField(blank=True, help_text='Escribe una reflexión libre sobre tu día.')),
                ('limito_socialmente', models.BooleanField(help_text='¿Respondiste solo, sin iniciar?', null=True)),
                ('check_in_energia', models.CharField(blank=True, choices=[('si', 'Sí, doy más de lo que recibo'), ('no', 'No, está equilibrado'), ('duda', 'No estoy seguro/a')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('membresia_activa', models.BooleanField(default=True)),
                ('fecha_vencimiento_membresia', models.DateField(blank=True, null=True)),
                ('proximo_registro_peso', models.DateField(blank=True, null=True)),
                ('peso_corporal', models.FloatField(blank=True, help_text='kg', null=True)),
                ('grasa_corporal', models.FloatField(blank=True, help_text='%', null=True)),
                ('cintura', models.FloatField(blank=True, help_text='cm', null=True)),
                ('pecho', models.FloatField(blank=True, help_text='cm', null=True)),
                ('hombro', models.FloatField(blank=True, help_text='cm', null=True)),
                ('cuello', models.FloatField(blank=True, help_text='cm', null=True)),
                ('biceps', models.FloatField(blank=True, help_text='cm', null=True)),
                ('antebrazos', models.FloatField(blank=True, help_text='cm', null=True)),
                ('caderas', models.FloatField(blank=True, help_text='cm', null=True)),
                ('muslos', models.FloatField(blank=True, help_text='cm', null=True)),
                ('gemelos', models.FloatField(blank=True, help_text='cm', null=True)),
                ('entrenos_perfectos', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='DietaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fin', models.DateField()),
                ('promedio_sueno', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promedio_rpe', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humor_dominante', models.CharField(choices=[('verde', '😊 Bien'), ('amarillo', '😐 Neutro'), ('rojo', '😞 Bajo')], max_length=20)),
                ('mensaje_joi', models.TextField(blank=True)),
                ('sugerencia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MiniReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('cumplido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(choices=[('peso', 'Peso (kg)'), ('grasa', 'Grasa corporal (%)'), ('cintura', 'Cintura (cm)')], max_length=20)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_actividad', models.CharField(max_length=20)),
                ('objetivo', models.CharField(max_length=20)),
                ('calorias_estimadas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gramos_proteinas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gramos_grasas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gramos_carbohidratos', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plan_generado_texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RevisionProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biceps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muslos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hombro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuello', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('antebrazos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('caderas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gemelos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaAceptada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('tipo', models.CharField(choices=[('subir', 'Subir carga'), ('bajar', 'Bajar carga'), ('mantener', 'Mantener carga')], max_length=20)),
                ('aceptada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
