# Generated by Django 5.2 on 2025-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='objetivo_principal',
            field=models.CharField(choices=[('hipertrofia', 'Hipertrofia Muscular'), ('fuerza', 'Ganancia de Fuerza'), ('perdida_peso', 'Pérdida de Peso'), ('resistencia', 'Mejora de Resistencia'), ('general', 'Salud General')], default='general', help_text='El objetivo principal del cliente para personalizar su experiencia.', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='clientes_fotos/default.png', null=True, upload_to='clientes_fotos/'),
        ),
    ]
