# Generated by Django 5.2 on 2025-06-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_bitacoradiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fin', models.DateField()),
                ('promedio_sueno', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promedio_rpe', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humor_dominante', models.CharField(choices=[('verde', '😊 Bien'), ('amarillo', '😐 Neutro'), ('rojo', '😞 Bajo')], max_length=20)),
                ('mensaje_joi', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
