# Generated by Django 5.2 on 2025-06-08 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_minireto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaAceptada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('tipo', models.CharField(choices=[('subir', 'Subir carga'), ('bajar', 'Bajar carga'), ('mantener', 'Mantener carga')], max_length=20)),
                ('aceptada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
