# Generated by Django 5.2 on 2025-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_sugerenciaaceptada'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='aprendizaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='check_in_energia',
            field=models.CharField(blank=True, choices=[('si', 'Sí, doy más de lo que recibo'), ('no', 'No, está equilibrado'), ('duda', 'No estoy seguro/a')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='cosas_positivas',
            field=models.TextField(blank=True, help_text='Escribe 3 cosas que funcionaron hoy.'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='emocion_dia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='limito_socialmente',
            field=models.BooleanField(help_text='¿Respondiste solo, sin iniciar?', null=True),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='mindfulness_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='mindfulness_pm',
            field=models.BooleanField(default=False),
        ),
    ]
