# Generated by Django 5.2 on 2025-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_bitacoradiaria_aprendizaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
