# Generated by Django 5.2 on 2025-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_bitacoradiaria_que_puedo_mejorar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='dolor_articular',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dolor articular de 0 a 10', null=True),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='energia_subjetiva',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Energía subjetiva de 0 a 10', null=True),
        ),
    ]
