# Generated by Django 5.2 on 2025-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_bitacoradiaria_autoconciencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='circunferencia_biceps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoradiaria',
            name='autoconciencia',
            field=models.TextField(blank=True, help_text='¿Qué emoción domina (0-10)?', null=True),
        ),
        migrations.AlterField(
            model_name='bitacoradiaria',
            name='descarga_cognitiva',
            field=models.TextField(blank=True, help_text='Escribe 5’ “lo que me preocupa AHORA”', null=True),
        ),
    ]
