# Generated by Django 5.2 on 2025-08-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisejercicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='anotacionentrenamiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cacheanalisis',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comparativarendimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='metarendimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='metricarendimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='prediccionrendimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='recomendacionentrenamiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tendenciaprogresion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='analisisejercicio',
            unique_together={('cliente', 'nombre_ejercicio', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='cacheanalisis',
            unique_together={('cliente', 'tipo_analisis', 'parametros_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='metricarendimiento',
            unique_together={('cliente', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='tendenciaprogresion',
            unique_together={('cliente', 'nombre_ejercicio', 'fecha_inicio', 'fecha_fin')},
        ),
    ]
