# Generated by Django 5.2 on 2025-06-24 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroWhoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('strain', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recovery', models.PositiveSmallIntegerField(help_text='Porcentaje')),
                ('horas_sueno', models.DurationField()),
                ('sueno_necesario', models.DurationField()),
                ('sleep_performance', models.PositiveSmallIntegerField(help_text='Porcentaje')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'fecha')},
            },
        ),
    ]
