# Generated by Django 5.2 on 2025-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='puntos_ganados',
            field=models.PositiveIntegerField(default=0, help_text='Puntos ganados por este entrenamiento'),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='records_rotos',
            field=models.PositiveIntegerField(default=0, help_text='Número de récords personales rotos en este entrenamiento'),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='volumen_total_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volumen total del entrenamiento en kg', max_digits=10),
        ),
    ]
