# Generated by Django 5.2 on 2025-07-02 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenorealizado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
