# Generated by Django 5.2 on 2025-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0002_entrenorealizado_puntos_ganados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='rpe_real',
            field=models.FloatField(blank=True, help_text='El RPE que el usuario sintió en esta serie', null=True),
        ),
    ]
