# Generated by Django 5.2 on 2025-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0002_registrowhoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrowhoop',
            name='hrv',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrowhoop',
            name='rhr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
