# Generated by Django 5.2 on 2025-07-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0002_alter_entrenorealizado_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenorealizado',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='entrenorealizado',
            name='volumen_total_formateado',
        ),
        migrations.AlterField(
            model_name='datosliftindetallados',
            name='entreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_liftin', to='entrenos.entrenorealizado'),
        ),
        migrations.AlterField(
            model_name='detalleejerciciorealizado',
            name='entreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ejercicio', to='entrenos.entrenorealizado'),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='calorias_quemadas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='fecha_importacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='frecuencia_cardiaca_maxima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='frecuencia_cardiaca_promedio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='fuente_datos',
            field=models.CharField(choices=[('manual', 'Manual'), ('liftin', 'Liftin')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='liftin_workout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='nombre_rutina_liftin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='notas_liftin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='tiempo_total_formateado',
            field=models.CharField(blank=True, help_text='Duración total en texto (ej: 1:10:23)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='volumen_total_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EjercicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_kg', models.FloatField(default=0)),
                ('series', models.PositiveIntegerField(default=1)),
                ('repeticiones', models.PositiveIntegerField(default=1)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('rpe', models.PositiveIntegerField(blank=True, null=True)),
                ('rir', models.PositiveIntegerField(blank=True, null=True)),
                ('fallo_muscular', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=True)),
                ('nuevo_record', models.BooleanField(default=False)),
                ('fuente_datos', models.CharField(default='manual', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_realizados', to='entrenos.entrenorealizado')),
            ],
        ),
    ]
