# Generated by Django 5.2 on 2025-07-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0003_alter_entrenorealizado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('grupo_muscular', models.CharField(choices=[('Pecho', 'Pecho'), ('Espalda', 'Espalda'), ('Piernas', 'Piernas'), ('Hombros', 'Hombros'), ('Bíceps', 'Bíceps'), ('Tríceps', 'Tríceps'), ('Glúteos', 'Glúteos'), ('Core', 'Core'), ('Cardio', 'Cardio'), ('Otros', 'Otros')], max_length=50)),
            ],
        ),
    ]
