# Generated by Django 5.2 on 2025-06-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0003_entrenorealizado_procesado_gamificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenorealizado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Entrenamiento Realizado', 'verbose_name_plural': 'Entrenamientos Realizados'},
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='calorias_quemadas',
            field=models.PositiveIntegerField(blank=True, help_text='Calorías quemadas durante el entrenamiento', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración del entrenamiento en minutos', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='fecha_importacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de importación desde Liftin', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='frecuencia_cardiaca_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia cardíaca máxima en BPM', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='frecuencia_cardiaca_promedio',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia cardíaca promedio en BPM', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='fuente_datos',
            field=models.CharField(choices=[('manual', 'Manual'), ('liftin', 'Liftin')], default='manual', help_text='Origen de los datos del entrenamiento', max_length=20),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='liftin_workout_id',
            field=models.CharField(blank=True, help_text='ID único del entrenamiento en Liftin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='notas_liftin',
            field=models.TextField(blank=True, help_text='Notas adicionales importadas de Liftin', null=True),
        ),
        migrations.CreateModel(
            name='DatosLiftinDetallados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_frecuencia_cardiaca', models.JSONField(blank=True, help_text='Array de datos de frecuencia cardíaca con timestamps', null=True)),
                ('version_liftin', models.CharField(blank=True, max_length=20, null=True)),
                ('dispositivo_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('sincronizado_health', models.BooleanField(default=False)),
                ('health_workout_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('metadatos_adicionales', models.JSONField(blank=True, help_text='Otros datos específicos de Liftin en formato JSON', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entreno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_liftin', to='entrenos.entrenorealizado')),
            ],
            options={
                'verbose_name': 'Datos Detallados de Liftin',
                'verbose_name_plural': 'Datos Detallados de Liftin',
            },
        ),
    ]
