# Generated by Django 5.2 on 2025-06-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0004_registrowhoop_eficiencia_sueno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrowhoop',
            name='estres_sueno',
        ),
    ]
