# Generated by Django 5.2 on 2025-06-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0004_alter_entrenorealizado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenorealizado',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Entrenamiento Realizado', 'verbose_name_plural': 'Entrenamientos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='estadoemocional',
            options={'verbose_name': 'Estado Emocional', 'verbose_name_plural': 'Estados Emocionales'},
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='fecha',
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de finalización del entrenamiento (ej: 10:46)', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio del entrenamiento (ej: 09:43)', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='nombre_rutina_liftin',
            field=models.CharField(blank=True, help_text='Nombre de la rutina como aparece en Liftin (ej: Día 6 - Full Body)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='numero_ejercicios',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de ejercicios realizados', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='tiempo_total_formateado',
            field=models.CharField(blank=True, help_text='Tiempo total como aparece en Liftin (ej: 1:02:23)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='volumen_total_formateado',
            field=models.CharField(blank=True, help_text='Volumen como aparece en Liftin (ej: 19K KG)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='volumen_total_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volumen total levantado en kg (ej: 19000.00 para 19K KG)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estadoemocional',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrenorealizado',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración total del entrenamiento en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='estadoemocional',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EjercicioLiftinDetallado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(help_text='Nombre del ejercicio como aparece en Liftin', max_length=200)),
                ('orden_ejercicio', models.PositiveIntegerField(default=1, help_text='Orden del ejercicio en la rutina')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso utilizado en kg', max_digits=8, null=True)),
                ('peso_formateado', models.CharField(blank=True, help_text='Peso como aparece en Liftin (ej: 268.5 kg, PC, 90-100 kg)', max_length=50, null=True)),
                ('series_realizadas', models.PositiveIntegerField(default=1, help_text='Número de series realizadas')),
                ('repeticiones_formateado', models.CharField(blank=True, help_text='Repeticiones como aparecen en Liftin (ej: 3x5-10, 3x10-12)', max_length=50, null=True)),
                ('repeticiones_min', models.PositiveIntegerField(blank=True, help_text='Repeticiones mínimas por serie', null=True)),
                ('repeticiones_max', models.PositiveIntegerField(blank=True, help_text='Repeticiones máximas por serie', null=True)),
                ('completado', models.BooleanField(default=True, help_text='Si el ejercicio fue completado exitosamente')),
                ('estado_liftin', models.CharField(choices=[('completado', '✓ Completado'), ('fallado', '✗ Fallado'), ('nuevo', 'N Nuevo'), ('parcial', '~ Parcial')], default='completado', help_text='Estado del ejercicio según Liftin', max_length=20)),
                ('notas_ejercicio', models.TextField(blank=True, help_text='Notas específicas de este ejercicio', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_liftin', to='entrenos.entrenorealizado')),
            ],
            options={
                'verbose_name': 'Ejercicio Detallado de Liftin',
                'verbose_name_plural': 'Ejercicios Detallados de Liftin',
                'ordering': ['entreno', 'orden_ejercicio'],
            },
        ),
    ]
