# Generated by Django 5.2 on 2025-07-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0005_grupomuscular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleejerciciorealizado',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenos.ejerciciobase'),
        ),
    ]
