# Generated by Django 5.2 on 2025-07-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0006_alter_detalleejerciciorealizado_ejercicio'),
        ('rutinas', '0003_ejerciciobase_alter_ejercicioenrutina_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpersonalizado',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejerciciobase'),
        ),
        migrations.AlterField(
            model_name='serierealizada',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejerciciobase'),
        ),
    ]
