# Generated by Django 5.2 on 2025-05-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('calorias_totales', models.PositiveIntegerField(help_text='Calorías por día (aprox.)')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('hora_aproximada', models.TimeField(help_text='Hora sugerida (ej. 08:00 AM)')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='dietas.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_asignadas', to='clientes.cliente')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietas.dieta')),
            ],
        ),
    ]
