# Generated by Django 5.2 on 2025-05-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_revisionprogreso'),
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='comida',
        ),
        migrations.AddField(
            model_name='dieta',
            name='calorias_totales',
            field=models.PositiveIntegerField(default=0, help_text='Calorías por día (aprox.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClienteDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_asignadas', to='clientes.cliente')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietas.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('hora_aproximada', models.TimeField(help_text='Hora sugerida (ej. 08:00 AM)')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='dietas.dieta')),
            ],
        ),
    ]
